# Generated by Django 3.2.3 on 2022-04-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='arrangements',
            constraint=models.UniqueConstraint(fields=('task', 'weekday'), name='unique'),
        ),
    ]
