# Generated by Django 3.2.3 on 2022-04-24 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_arrangements_unique'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='arrangements',
            unique_together=set(),
        ),
    ]
