from .task_view_set import TaskViewSet
from .student_view_set import StudentViewSet
from .teacher_view_set import TeacherViewSet
from .stundet_task_view import StudentTaskView
from .week_task_view import WeekTaskView
from .arrangements_update_view import ArrangementsUpdateView
from .arrangements_update_today_view import ArrangementsUpdateTodayView